server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVER:localhost}:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: review
          uri: lb://review
          predicates:
            - Path=/products/{id}/reviews/**
        - id: product
          uri: lb://product
          predicates:
            - Path=/products/**
#         - id: product
#           uri: lb://product
#           predicates:
#             - Path=/products/**
#           filters:
#             - RewritePath=/product/(?<segment>.*), /$\{segment}
#         - id: review
#           uri: lb://review
#           predicates:
#             - Path=/product/**
#           filters:
#             - RewritePath=/review/(?<path>.*), /$\{path}
        - id: register
          uri: lb://register
          predicates:
            - Path=/register/**

management:
  endpoints:
    web:
      exposure:
        include: gateway

