server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: product
          uri: lb://product
          predicates:
            - Path=/products/**
#           filters:
#             - RewritePath=/products/(?<segment>.*), /$\{segment}
        - id: review
          uri: lb://review
          predicates:
            - Path=/**
#           filters:
#             - RewritePath=/products/(?<path>.*), /$\{path}

management:
  endpoints:
    web:
      exposure:
        include: gateway

